- webapp/nbdimeserver.py
Adds the option to specify a port number for the web app.
Filed in response to:
```
cwd = os.path.abspath(os.path.curdir)
main(port=8888, cwd=cwd, outputfilename="")
```
Let me know if you'd like me to iterate on it. Cheers from Jupyter Day Chicago!
> Add command line arg for webserver port

- nbdime/diff_format.py
- nbdime/diffing/lcs.py
- nbdime/diffing/seq_difflib.py
- nbdime/diffing/snakes.py
- nbdime/merging/autoresolve.py
- nbdime/merging/generic.py
- nbdime/merging/notebooks.py
- nbdime/patching.py
- nbdime/tests/test_merge.py
- nbdime/tests/test_merge_notebooks.py
This provides an initial implementation of an autoresolve feature with strategies configurable per path in json document. Good handling of source and outputs of notebooks is _not_ in place yet, but clearing differing execution_count and using base value in case of conflicting notebook or cell metadata should in principle work. Some basic tests are in place but more testing is needed.
> Work on merge and strategies for automatic conflict resolution

- nbdime/prettyprint.py
- nbdime/tests/test_prettyprint.py
- setup.py
This imporves the terminal representation of notebook diffs, e.g. when used as `git difftool`
- nicer representations of simple dicts
- special handling for cells, outputs
- elide base64 strings
- indentation
- call [git ]diff for diffs of text fields
> work on pretty-printed diffs

- .travis.yml
- nbdime/diff_format.py
- nbdime/diffing/generic.py
- nbdime/diffing/lcs.py
- nbdime/diffing/notebooks.py
- nbdime/diffing/seq_difflib.py
- nbdime/diffing/snakes.py
- nbdime/merging/autoresolve.py
- nbdime/merging/chunks.py
- nbdime/merging/generic.py
- nbdime/merging/notebooks.py
- nbdime/patching.py
- nbdime/prettyprint.py
- nbdime/tests/fixtures.py
- nbdime/tests/test_diff.py
- nbdime/tests/test_diff_json_conversion.py
- nbdime/tests/test_merge.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/tests/test_patch.py
- nbdime/tests/test_prettyprint.py
- nbdime/utils.py
- pytest.ini
Sorry for the big collection of changes in one PR.
This implements an improved merge algorithm for lists, although still not perfect.
Adds safety checks, documents some code a bit better, and various minor things.
I think this solves shifting of indices in conflicts remaining after merge and autoresolve:
https://github.com/jupyter/nbdime/issues/34
At least some cases of conflicts on adjacent changes (some more cases should probably fail):
https://github.com/jupyter/nbdime/issues/32
Most of the merge strategy options (not configurable) with somewhat sensible notebook defaults:
https://github.com/jupyter/nbdime/issues/19
And json patch conversion with index shifting:
https://github.com/jupyter/nbdime/issues/15
Although all of these need more testing before being trustworthy.
> Improved list merge algorithm and autoresolve + various minor things

- nbdime/prettyprint.py
- nbdime/tests/test_prettyprint.py
> Congrats on inclusion in `jupyter`! :cake:
On a vanilla Windows install, `diff` is not available, so `test_present_string_diff` will always fail.
This adds a fallback based on stdlib `difflib.unified_diff`, and accepts either unified or diff-default.
Another approach would be to always use `diff -u` (and keep the fallback) but just always assume unified diff.
> prettydiff fallback

- .gitattributes
- nbdime/gitdiffdriver.py
- nbdime/tests/test_git_diffdriver.py
- setup.py
Adds a notebook diff driver for git, which produces a diff for notebooks only. This can be used by `git diff` (as compared to `git difftool`), and relies on filename filtering in `.gitattributes` to be supplied the right files. The `.gitattributes`need to be configured for each repo, but the line included in this PR's `.gitattributes` file should be sufficient (`*.ipynb	diff=jupyternotebook`).
Also added a test that mocks a call by git to the diff driver, comparing the output. Currently it has to use coloring characters to match the captured output, but I'm not sure if this is correct/expected for all setups?
> Git diff driver

- nbdime/prettyprint.py
- nbdime/tests/test_git_diffdriver.py
Remove `--color-word` argument when prettyprinting diff for test, in order to avoid coloring characters in captured output. See #44.
> Remove `--color-words` when testing

- nbdime/diffing/notebooks.py
- nbdime/tests/files/error-1.ipynb
- nbdime/tests/files/error-2.ipynb
Currently, the `error` `output_type` is not handled, and causes a nasty error as it is assumed to be a mime-bundle... but doesn't have the `data` key.
This adds (initially) a pair of notebooks containing some tracebacks. A proposed solution coming after we have a failing test to look at!
> Handle error output_type

- nbdime/webapp/nbdifftool.py
rather than strings that need casting
> Use integer port arguments in nbdifftool

- nbdime/webapp/nbdifftool.py
for now, while we can't handle them
closes #52
> skip non-notebook files in nbdifftool

- README.md
- setup.py
See Issue #51.
I have added a command for running `npm install` and `npm build` during setup.py. The command is set to be run automatically on `build`, `develop`, and `sdist`. The code is mainly inspired by the similar code for jupyterlab, https://github.com/jupyter/jupyterlab/blob/master/setup.py
For now, the `npm install` checks for the `node_modules` directory, and runs if that directory does not exist, while `npm build` runs every time. There might be better ways to trigger this (I am not very familiar with node)?
> Added a command to setup.py to run npm install and build

- nbdime/webapp/src/diffmodel.ts
- nbdime/webapp/src/widgets.ts
Previously this would fail the assert in `createPatchDiffModel()` for empty diffs in the assert.
> Handle empty root metadata diff

- nbdime/__main__.py
- nbdime/args.py
- nbdime/gitdiffdriver.py
- nbdime/gitdifftool.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
… exit.
Also enable help text for all apps.
Canonical pattern:
def main(args=None):
if args is None:
args = sys.argv[1:]
...
return returncode
Outside of `__main__`, there's no need to have `if __name__ ==
"__main__"`.
With the addition of __main__, you can now do:
python -m nbdime nbdiff <args>
instead of
nbdiff <args>
which may be convenient to test with different python versions.
There is still some confusion about where --base --local --remote
are defined, I tried fixing a failure one place but the args.py utils
are not used consistently.
> Consistency fixes in CLI tools

- nbdime/gitdifftool.py
- nbdime/gitmergetool.py
As tools cannot differentiate on file type/extension, it doesn't make sense to register them as default tools. This changes the default `config --enable` command to simply register the tool, unless the flag `--set-default` is also specified. For simplicity, the storing/retrieving of the previous default is removed, but I'm willing to put this back in if someone feels strongly about this :)
> Change how diff/merge tools register

- nbdime-web/src/diff/util.ts
Fix a regression based on a flawed assumption. This PR fixes the code, and adds a comment explaining the correct assumptions.
> Fix overlap check in `flattenStringDiff`

- nbdime-web/src/merge/widget.ts
- nbdime-web/src/styles/merge.css
We previously relied on internals of `OutputAreaModel`/`OutputAreaWidget` as a workaround while waiting for jupyterlab/jupyterlab#855. With that merged and released, we now instead extend the classes to support reordering of outputs. Fixes #93.
Also updates styling of drag images.
> Fix output drag and drop

- nbdime/gitdiffdriver.py
- nbdime/gitmergedriver.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/prettyprint.py
- nbdime/tests/files/unicode--1.ipynb
- nbdime/tests/files/unicode--2.ipynb
- nbdime/tests/fixtures.py
- nbdime/tests/test_diff_format.py
- nbdime/tests/test_merge_format.py
- nbdime/webapp/nbdimeserver.py
- setup.py
Fixes nbdiff on commandline with notebooks containing unicode chars.
> Use io.open with utf-8 encoding everywhere

- nbdime/gitmergetool.py
it should be `base local remote` but was `local remote base`.
Need to re-run `nbmergetool config --enable` to get the change.
> fix argument ordering in mergetools

- nbdime/gitdifftool.py
- nbdime/gitmergetool.py
Previously, the option `set_default` of the tool config CLI was not passed to the actual config function, so the tools were never registered as the default.
> Pass `set_default` flag to tool config function

- nbdime-web/src/diff/model.ts
Previous values passed to `makeOutputModels()` indicated a deleted cell. Now correctly checks for presence of diff on outputs.
Fixes #108.
> Fix unchanged outputs in patched cell

- nbdime-web/src/common/exceptions.ts
- nbdime-web/src/diff/model/cell.ts
- nbdime-web/src/diff/model/output.ts
- nbdime-web/src/merge/model/common.ts
- nbdime-web/test/karma.conf.js
- nbdime-web/tsconfig.json
- nbdime/webapp/package.json
- nbdime/webapp/src/app/common.ts
- nbdime/webapp/src/index.ts
- nbdime/webapp/src/tsconfig.json
- nbdime/webapp/src/typings.d.ts
- nbdime/webapp/typings/alertify.js.d.ts
Adds a custom exception type, and a global exception handler that will display those errors to the user.
Adds an npm dependcy to `alertify.js` for displaying notifications (DOM-based).
> Add error notifications in web-views

- nbdime-web/src/merge/model/notebook.ts
- nbdime-web/test/src/merge/model.spec.ts
Merge decisions need to be split onto cells in the web view (such that no decision affects more than one cell), which is done during pre-processing of the decisions. One category of multi-cell decisions had been forgotten, which this PR adds support for.
> Fix splitting of decisions in web-merge

- nbdime-web/src/common/mergeview.ts
- nbdime-web/src/common/util.ts
- nbdime-web/src/diff/util.ts
- nbdime-web/src/merge/decisions.ts
- nbdime-web/src/merge/model/common.ts
- nbdime-web/src/styles/common.css
- nbdime-web/src/styles/merge.css
- nbdime/merging/chunks.py
- setup.cfg
Fix some css so that the CodeMirror gutter markers for picking a chunk and for flagging conflicts align with the top of the chunk in all views. Also fix some other styling for chunk visualization.
> Fix gutter marker alignments

- nbdime/prettyprint.py
- nbdime/tests/conftest.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_prettyprint.py
The fallback method when `git` and `diff` commands are not present did not previously use `colorama` for color highlighting. Also updated to avoid disk I/O when using the fallback.
> Fix colorama highlighting of multiline string

- nbdime-web/src/diff/model/string.ts
- nbdime-web/src/diff/widget/cell.ts
- nbdime-web/src/merge/model/common.ts
- nbdime-web/src/patch/index.ts
- nbdime/diffing/notebooks.py
- nbdime/tests/files/single_cell_nb--json_output.ipynb
- nbdime/tests/files/single_cell_nb--json_output_changed.ipynb
Tune the diffing algorithm to better handle JSON output types, and tune the text presentation of it (also fixing one or two bugs in web code). Web presentation will likely need to be revisited once JSON rendering support in Jupyterlab is included.
> Improve support for JSON output type

- nbdime/diffing/notebooks.py
- nbdime/merging/notebooks.py
- nbdime/prettyprint.py
- nbdime/tests/files/attachment--change_attachment.ipynb
- nbdime/tests/files/attachment--remove_attachment.ipynb
- nbdime/tests/files/attachment.ipynb
- nbdime/tests/test_prettyprint.py
- nbdime/utils.py
Improves support for the `attachments` field in the python code (http://nbformat.readthedocs.io/en/latest/format_description.html#cell-attachments). Includes changes to the `prettyprint` code in order to detect attachments fields and apply base64 snipping to its mime data.
Support in the web-code will be added in a separate PR.
> Improve  `attachments` cell field handling

- setup.py
There should be fewer different circumstances to handle:
- always use setuptools
- disable implicit bdist_egg (this is the main reason to avoid setuptools)
- wrap build_ext instead of build & develop (build_ext is called before both)
- simplify skip_npm handling: perform the skip in the npm-using commands, rather than changing what commands exist.
> simplify conditions in setup.py

- nbdime/__main__.py
- nbdime/args.py
- nbdime/diff_format.py
- nbdime/merging/notebooks.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/nbshowapp.py
- nbdime/prettyprint.py
- nbdime/tests/conftest.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_prettyprint.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- setup.py
Rework prettyprinting of diffs, used by `nbdiff` cli tool.
Besides refactoring, changes include a lot of formatting details,
showing md5 of differing base64 data instead of snippets,
and adding timestamp of files in diff header.
Add printing of merge decisions, used by `nbmerge` cli tool if no output filename provided.
Add a command `nbshow` to display notebook or just parts of it on terminal,
e.g. `nbshow -soa nb.ipynb` to display source, output and attachments.
This uses the same prettyprinting tools as nbdiff.
> Prettyprint notebooks and decisions

- docs/source/conf.py
- docs/source/index.rst
- docs/source/installing.rst
Pretty heavy edit of content in `index.rst` and `installation.rst` and minor edits to `conf.py`.
- `index.rst` mostly styling and grammar consistency for reader
- `installation.rst` updated installation instructions for virtualenv for Python 2 and Python 3
Do we want to revisit which versions of Python 2 and Python 3 are supported?
> Update documentation for installation and index intro

- docs/source/cli.rst
- nbdime/args.py
- nbdime/merging/autoresolve.py
- nbdime/merging/notebooks.py
- nbdime/tests/fixtures.py
- nbdime/tests/test_autoresolve.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/utils.py
Refactor the CLI for merge strategies.
- Limit applicable CLI merge strategies to "use-base", "use-local", "use-remote", "union",  or "inline".
- Functions also accept "mergetool" as strategy.
- Flag `--no-ignore-transients` : Disallow clearing/ignoring of transient data on conflicts.
- Added `--input-strategy`/`--output-strategy`, that takes the same values as `--merge-strategy`, but will override strategy for source/outputs, respectively.
Fixes #19.
> Merge strategies CLI

- nbdime/merging/generic.py
- nbdime/tests/files/apap--1.ipynb
- nbdime/tests/files/apap--2.ipynb
- nbdime/tests/files/apap--3.ipynb
- nbdime/tests/files/apap.ipynb
- Adds some test files which gives AP/AP conflicts (with either differing or identical patch ops).
- Fixes handling of such conflicts.
Note that the implemented handling of such conflicts for strings is a temporary fix in wait of a more complete overhaul of string diff chunking.
> Fix autoresolve of addrange+patch vs addrange+patch conflicts

- nbdime-web/src/common/collapsible.css
- nbdime-web/src/common/dragpanel.ts
- nbdime-web/src/diff/widget/cell.ts
- nbdime-web/src/merge/model/cell.ts
- nbdime-web/src/merge/widget/cell.ts
- nbdime-web/src/merge/widget/common.ts
- nbdime-web/src/merge/widget/notebook.ts
- nbdime-web/src/merge/widget/output.ts
- nbdime-web/src/styles/diff.css
- nbdime-web/src/styles/merge.css
- nbdime-web/src/styles/variables.css
- nbdime/webapp/src/app/diff.css
- nbdime/webapp/src/app/merge.css
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
Fixes #120.
- Added "clear outputs" checkbox on merged cells with outputs.
- "Trash can" drop zone appears when dragging output from merged outputs.
- Adjust styling/rendering of outputs in merge view
> Web merge: Clear outputs

- pytest.ini
it adds loads of noise if on by default.
it can still be used on request if needed.
> remove `-l` option from pytest.ini

- nbdime/prettyprint.py
- nbdime/tests/test_autoresolve.py
should avoid introducing `\r\n` into notebooks when inlining conflicts on Windows
> normalize newlines in external_merge_render

- nbdime/gitmergetool.py
we aren't storing previous, so it doesn't make sense to restore from it
> remove unused restoration of previous merge.tool

- nbdime/__main__.py
Closes #182 
Adds a user friendly, verbose CLI help message when user enters any of the following:
- `nbdime -h`
- `nbdime` with no additional options
- `nbdime kjlkjlj` incorrect command
For `nbdime --version`, version is returned.
> Enhance CLI help message

- nbdime-web/src/common/mergeview.ts
- nbdime-web/src/styles/merge.css
Previously, using a mergeview picker (arrows on side of local/base/remote), would uncollapse merged view. This change ensures that unchanged areas stay collapsed.
> Fix picking vs hidden unchanged stretches

- nbdime-web/package.json
Typescript 2.1 is out, and current code base does not build on it. Narrow the range of valid typescript versions for now, as some issues in TS 2.1 should be fixed before transitioning.
> Lock typescript version to 2.0.x

- nbdime/webapp/package.json
Missing change to #200, should fix #201.
> Fix typescript lock to 2.0.x

- appveyor.yml
Adds a configuration for running CI on appveyor.
Includes #203 as it would otherwise be prevented from running tests.
TODO:
> Appveyor CI

- docs/source/testing.rst
You have to run JS tests from `nbdime-web` directory, not the root directory.
> Fix JS testing instructions

- nbdime-web/src/diff/widget/cell.ts
- nbdime-web/src/styles/diff.css
- nbdime/webapp/src/app/common.css
- Switch to using sans-serif font to match jupyterlab/notebook
- Float input prompt to the left for unchanged cells
- Remove border between consecutive unchanged cells
- Add border around source block of unchanged cells, similar to that of jupyterlab
Fixes #212.
> Adjust web diff styles

- nbdime/__main__.py
- nbdime/gitdifftool.py
- nbdime/gitmergetool.py
Fixes the `nbdime mergetool` command, which previously pointed to the wrong tool name.
Also removes some unused imports.
> Fix nbdime mergetool

- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/src/app/common.css
- nbdime/webapp/src/app/compare.ts
- nbdime/webapp/src/app/diff.css
- nbdime/webapp/src/app/merge.css
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
Adds a button to the web merge interfaces, which allows the user to download (strictly: save from local javascript state) the merge result.
A possible improvement on the current behavior is to also treat directories correctly, although that will require the server to expose the current directory. I am not sure about the security implications of that.
Resolves #121.
> Download merge button

- nbdime/utils.py
Git's default location for the attributes file is not `~/.gitattributes`. Update nbdime's default to reflect the one described [here](https://git-scm.com/docs/gitattributes). Addresses #219.
> Fix default location of global gitattributes file

- nbdime-web/src/diff/model/output.ts
- nbdime-web/src/diff/widget/output.ts
Adds missing wiring for rendering error outputs. Previously error outputs were simply shown as raw JSON.
> Render error tracebacks

- nbdime-web/src/diff/widget/renderable.ts
Fixes #224.
In the future, we should add an indicator if a non-preferred MIME type was selected or output was sanitized, and add the option for the user to trust single/all outputs.
> Render output as long as one MIME-type is safe

- nbdime/args.py
- nbdime/gitdiffdriver.py
- nbdime/gitdifftool.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/tests/test_utils.py
- nbdime/utils.py
Resolves #225.
Adds `--system` flag to `config` subcommand of gitdiffdriver, gitdifftool, gitmergedriver and gitmergetool. 
It extracts the shared parts of the `config` subcommand to `args.py` for ease of maintenance, although this leads to somewhat large function calls.
> Add `--system` flag for git config commands

- setup.py
Closes #247. (Hopefully! Works for me.)
It's unclear if this was a typo or misunderstanding, but AFAICT
python's glob implementation does not properly support double-star
(``**``) globbing.
At any rate, you can test this easily:
ipython -c "import glob; glob.glob('nbdime/webapp/static/**/*.*')"
Out[1]: []
ipython -c "import glob; glob.glob('nbdime/webapp/static/*.*')"
Out[1]:
['nbdime/webapp/static/nbdime.js',
'nbdime/webapp/static/1.nbdime.js.map',
'nbdime/webapp/static/1.nbdime.js',
'nbdime/webapp/static/nbdime.js.map',
'nbdime/webapp/static/fa396483b7ade73b4727bad6aa027a35.html']
Edited to add: Note that the static files **were** getting included in the sdist, thanks to the ``graft nbdime/webapp`` in MANIFEST.in. But that only guarantees inclusion in the tarball - they have to be …
> Packaging / bugfix: Fix Typo in setup.py ``package_data`` entries.

- .travis.yml
- appveyor.yml
Git should be updated in appveyor/ci#1214, so no longer need to manually perform installation step.
> Remove appveyor install of explicit git version

- nbdime/args.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- nbdime/webapp/webutil.py
Adds an argument `--ip` to all web entry points (and similarly, `nbdimeserver` accepts an `ip` keyword), such that the listening interface can be specified.
Resolves #244.
Security note: As nbdime has no authentication built in, this might lead to exposing parts of your file system to an outsider, so this option should be used with care.
> Add `--ip` option to web entries

- nbdime-web/src/common/mergeview.ts
- nbdime/webapp/package.json
- nbdime/webapp/src/app/common.css
- nbdime/webapp/src/app/common.ts
- nbdime/webapp/src/app/compare.ts
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/src/app/staticdiff.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
Adds a button "Export" to web-diff views (once it has completed rendering the entire diff), which will download a self-containing HTML page of the diff view. This can then be shared with others that do not have nbdime installed.
Also now shows a spinner while loading/rendering diff/merge.
Related to #251.
> Web: Export static diff

- nbdime/gitdifftool.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/tests/test_cli_apps.py
- nbdime/utils.py
- nbdime/webapp/nbdimeserver.py
Adds handling of explicitly non-existing files, e.g. for when a file has been added/deleted. On *nix this is marked by "/dev/null" while on Windows this is marked by "nul" (reserved name).
Fixes #259.
> Handle null files (/dev/null | nul)

- .travis.yml
It seems Travis runs `before_cache` before `after_success`! Therefore, the cache cleanup happened before the `cd..` to the expected directory.
> Fix Travis JS/TS stale caches

- nbdime-web/src/common/dragpanel.ts
- nbdime/diff_format.py
- nbdime/diffing/generic.py
- nbdime/diffing/notebooks.py
- nbdime/diffing/snakes.py
- nbdime/merging/decisions.py
- nbdime/merging/generic.py
- nbdime/profiling.py
- setup.py
This extracts the bug-fixes and simple improvements from #237 for eased review. Should also simplify the diff of #237.
> Various fixes and minor adjustments

- nbdime/webapp/src/app/compare.ts
Fixes #266.
Export diff button was not wired up on index page, only on `/diff`.
> Enable export diff on compare page as well

- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/nbshowapp.py
- nbdime/tests/test_cli_apps.py
- nbdime/utils.py
rather than raising UnicodeEncodeErrors.
closes #101
Need to do a bit of testing on Python 2 and Windows to ensure this is right everywhere.
> escape encoding errors when presenting diffs/output

- nbdime-web/src/common/util.ts
- nbdime-web/src/merge/decisions.ts
- nbdime-web/src/merge/model/cell.ts
- nbdime-web/src/merge/model/notebook.ts
- nbdime/tests/test_decision_tools.py
Fixes #238.
Fixes two issues in web-merge:
- Uses stable sort for sorting decisions. This is not guaranteed for javascripts `Array.sort`.
- Ensures that `CellDiffModel.splitPatch()` returns sorted decisions. The extra sort step was needed since we split the diff.
> Fix web-merge decision align

- docs/source/installing.rst
Avoids "Could not detect requirement name, please specify one with #egg="
closes #274
> add missing #egg=nbdime to pip install -e

- nbdime/args.py
- nbdime/diffing/notebooks.py
- nbdime/gitmergedriver.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbshowapp.py
- nbdime/tests/files/mixed-conflicts--1.ipynb
- nbdime/tests/files/mixed-conflicts--2.ipynb
- nbdime/tests/files/mixed-conflicts--3.ipynb
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
Adds flags to diff/merge apps to selectively perform diff/merge on source, outputs, attachments, metadata, or any combination of these. 
Examples:
```
nbdiff a.ipynb b.ipynb -s    # Only considers source for diff
nbdiff a.ipynb b.ipynb -o    # Only considers outputs for diff
nbdiff a.ipynb b.ipynb -O    # Considers everything *except* outputs for diff
nbdiff a.ipynb b.ipynb --ignore-outputs    # Long form of previous
nbdiff a.ipynb b.ipynb -sm    # Only considers source and metadata for diff
nbdiff a.ipynb b.ipynb -sM    # Will give an error, as combination of flags doesn't make sense
```
`nbmerge ` will take the same flags (anything not covered by flags should keep base value).
(Note that due to an detail of how the differ lookup works, cell's `execution_count` does not currently fall …
> Diff options

- docs/source/index.rst
- docs/source/vcs.rst
- nbdime/args.py
- nbdime/gitfiles.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/tests/conftest.py
- nbdime/tests/test_autoresolve.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_diff_gitrefs.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_utils.py
- nbdime/tests/test_web.py
- nbdime/utils.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- setup.py
As git's difftool does not work concurrently with diff driver installed, we allow nbdiff-web to take git refs. For consistency, nbdiff has also been modified to accept them.
Fixes #147.
> Allow nbdiff[-web] to take gitrefs

- nbdime-web/src/diff/widget/cell.ts
- nbdime-web/src/merge/widget/cell.ts
- nbdime-web/src/merge/widget/common.ts
- nbdime-web/src/styles/diff.css
- nbdime-web/src/styles/merge.css
- nbdime/webapp/src/app/common.ts
- nbdime/webapp/src/app/compare.ts
- nbdime/webapp/src/app/diff.css
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.css
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
Allows hiding unchanged cells in both diff and merge. Replaces the ranges of hidden, unchanged cells with a marker that says "X unchanged cell(s) hidden".
Fixes #272.
> Webapps: Add checkbox to hide unchanged cells

- nbdime/diffing/notebooks.py
- nbdime/profiling.py
- setup.py
It seems that with the hierarchical algorithm we end up comparing the same things several times. Due to their low level in the hierarchy, and comparatively large size, MIME data comparisons are especially affected by this. This PR addresses this by simply adding an LRU cache on the MIME data comparison.
Related to #237.
> Add caching for mimedata comparison

- setup.py
- setupbase.py
Use setupbase.py from jupyter-packaging.
This should also fix the issue that @martinal experienced where a `pip install .` from the repo would not include the built files (via the implicit call to `update_package_data()`).
> Refactor setup.py code to use jupyter-packaging

- nbdime/gitdiffdriver.py
- nbdime/tests/test_git_diffdriver.py
When gitdiffdriver hands off to nbdiffapp, ignore flags (like`--ignore-metadata`) are dropped because of a bug that does not distinguish between False (an ignore flag is passed) and None (neither an ignore flag nor its opposite are passed). This prevented use of ignore flags from being usable in a gitconfig file.
> Fix mishandled ignore flags

- nbdime/gitfiles.py
- setup.py
GitPython has fixed an error in version 2.1.4 - 2.1.6 in which a missing git command would prevent nbdime from working at all if git was missing. This has now been fixed, so updating the requirement spec.
Ref #295.
> Update GitPython version requirement

- nbdime/gitfiles.py
- nbdime/tests/test_diff_gitrefs.py
- nbdime/webapp/nbdimeserver.py
Fixes two bugs when using built-in git support to diff against working directory:
- The difftool was checking the type of the wrong argument, leading to an exception. See #304.
- When running a diff in a subdirectory, it would treat the file as deleted (it could not find the file as it was looking in the wrong spot).
Fixes #304.
> Fix difftool against working dir + diff against working dir in subfolder

- nbdime/args.py
- nbdime/merging/notebooks.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbshowapp.py
- nbdime/prettyprint.py
- nbdime/tests/test_merge_notebooks_inline.py
- nbdime/tests/test_prettyprint.py
Overhauls the pretty-print system in order to filter diffs properly according to ignore flags to diff. Also adds the `-d`/`--details` flag to nbdiff for filtering similar to what is available in `nbshow`.
Possible breaking change in CLI arguments: Removed the `-d` short-hand for `--decisions` to nbmerge, as it now conflicts with the `--details` flag's short-hand for diff filtering.
Note that the filtering is still not fully applied for nbdiff-web, which should probably be solved in a different PR.
Fixes #303.
> Fix pretty-print diff filtering for added/removed cells etc.

- appveyor.yml
Might cause wrong python executable to used if this is not set.
> Ensure appveyor python root folder is on path

- docs/source/index.rst
This looks like a typo where 'nbdime-web' was entered, which doesn't exist, instead of 'nbdiff-web'.
> Fix apparent typo of nbdiff-web

- nbdime/webapp/src/index.ts
- nbdime/webapp/templates/nbdimepage.html
- packages/nbdime/src/common/mergeview.ts
- packages/nbdime/src/diff/model/cell.ts
- packages/nbdime/src/diff/model/notebook.ts
- packages/nbdime/src/diff/widget/cell.ts
- packages/nbdime/src/diff/widget/common.ts
- packages/nbdime/src/diff/widget/notebook.ts
- packages/nbdime/src/styles/diff.css
Chunks blocks of added/removed cells (or outputs) together, allowing them to be shown side-by-side in the web diff. Also adds styling rules so that side-by-side is not used on smaller screens (the removed block is then shown first, followed by the added block).
Also includes a fix for when the first line-number of added/deleted source was hidden.
Fixes #299.
> Web diff: Show consequent added/removed cells/outputs side-by-side

- nbdime/args.py
- nbdime/nbdiffapp.py
- nbdime/prettyprint.py
- nbdime/tests/test_cli_apps.py
- nbdime/vcs/git/diffdriver.py
- nbdime/vcs/hg/diff.py
Adds an argument to CLI diff entry points, which controls whether any calls out to `git diff` will use the `--color-words` argument. Off by default, due to its white-space stripping nature, c.f. #293, but can now be turned back on manually (opt-in).
Fixes #293.
> Add --color-words to CLI diff entry points

- packages/nbdime/src/diff/model/output.ts
- packages/nbdime/src/styles/diff.css
- Updates MIME type check to follow update in jupyterlab dependency.
- Ensures images in unchanged outputs are centered, *without* centering unchanged text outputs.
> Web: Render fixes

- nbdime/webapp/src/app/common.ts
- nbdime/webapp/src/app/diff.css
- packages/nbdime/src/diff/model/notebook.ts
- packages/nbdime/src/diff/widget/notebook.ts
Fixes #325.
Fixes the following issues introduced in #317:
- Patches no longer chunk with directly preceding additions (i.e. presentation cell chunks in web view).
- "N unchanged cells hidden" pseudo-elements are now added to chunk element if appropriate, in order to ensure a full width banner as expected.
Screenshot of fixed layout, corresponding to broken one in #325.
> Fix chunking of patched cells + CSS

- nbdime/webapp/nbdimeserver.py
Would cause `AttributeError` for anyone on notebook less than version 5.
> Polyfill mathjax config for older notebook versions

- nbdime/webapp/nbdimeserver.py
Ensures that server checks for signals every 5 seconds on Windows. Needed to pick up e.g. Ctrl + C events.
>  Add periodic poll on server 

- nbdime/webapp/nb_server_extension.py
Do not assume that the current loader is a FileSystemLoader by trying to modify its search path. Instead, use a ChoiceLoader that use our own FileSystemLoader unless it has been overridden (i.e. defined by any other loader).
The previous behavior caused `AttributeError` whenever the loader was not a `FileSystemLoader`, e.g. when using jupyterhub.
> Use a ChoiceLoader for jinja2 templates

- nbdime/gitfiles.py
- nbdime/notebook_ext/index.js
- nbdime/webapp/nb_server_extension.py
Improves the error reporting for the extensions:
- Server handler message is informative when git diffing fails due to missing git executable.
- Notebook extension handler error is informative if it suspects the server extension is not installed (404). Also disables the button.
> Improve error feedback for extensions

- nbdime/args.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
Disables remote shutdown of web tools. Useful for e.g. debugging, but might have other uses.
> Add --persist flag to web tools

- .gitignore
- docs/source/merging.rst
- nbdime/merge_format.schema.json
- nbdime/merging/chunks.py
- nbdime/merging/decisions.py
- nbdime/merging/generic.py
- nbdime/merging/notebooks.py
- nbdime/merging/strategies.py
- nbdime/prettyprint.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/tests/test_merge_notebooks_inline.py
- nbdime/tests/utils.py
- packages/nbdime/src/merge/decisions.ts
- Add an optional field `similar_insert` on merge decision. This is used when there are two conflicting inserts that are deemed to be similar. In that case, this field stores their relative difference (local vs remote).
- Add an internal merge strategy `inline-cell`, used with the CLI `inline` strategy. For conflicting concurrent inserts, this does one of two things:
- For non-similar insertions, it adds merge markers around the cells (`<<<<<<< local` etc), and then includes the local insertion and remote insertion).
- For similar insertions, it inserts a cell while recursing to use merge markers for source / output / metadata similar to other existing inline strategies.
Screenshot of non-similar insertion of markdown cells with `inline-cell` strategy:
Ref #345.
> Handle concurrent inserts

- nbdime/args.py
- nbdime/gitfiles.py
- nbdime/tests/filters/add_helper.py
- nbdime/tests/filters/noop.py
- nbdime/tests/filters/strip_outputs.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_git_filter_integration.py
- nbdime/utils.py
- nbdime/vcs/git/diffdriver.py
- nbdime/vcs/git/difftool.py
- nbdime/vcs/git/filter_integration.py
- nbdime/vcs/git/mergedriver.py
- setup.py
- Adds capability for applying git filters according to git config.
- Applies filter on remote as it should for calls to `nbdiff` with git refs.
- As diff drivers/tools cannot correctly apply filters, it will always apply any filter on remote if the flag `--use-filter` is given, otherwise it will not consider filters.
> Add git filter integration

- nbdime/diffing/generic.py
- nbdime/diffing/notebooks.py
- nbdime/utils.py
Make it easier to configure ignores for diffs in a generic manner, while still retaining the utility function `set_notebook_diff_targets`.
> Generic ignore configuration function

- nbdime/diffing/generic.py
The get method side-steps the default factory on the defaultdict, as specified in python docs. This prevented the use of `diff_sequence_multilevel` in certain cases, and of `diff_attachments` on attachments.
> Don't use get on defaultdict

- nbdime/args.py
- nbdime/config.py
- nbdime/tests/test_args.py
Allows for using the config system for full configuration of keys to ignore. This should be a better long term solution than adding more logic to ignore flags on the CLI.
> Custom ignore config

- docs/source/extensions.rst
Minor documentation fix: "the the" -> "the".
> Fix double word typo in the documentation

- packages/nbdime/src/common/util.ts
- packages/nbdime/src/diff/model/output.ts
- packages/nbdime/src/diff/model/renderable.ts
- packages/nbdime/src/diff/widget/output.ts
- packages/nbdime/src/merge/model/notebook.ts
- packages/nbdime/test/src/common/flexpanel.spec.ts
- packages/nbdime/test/src/merge/decisions.spec.ts
Fixes an issue with outputs where the MIME type contains a '.' (e.g. 'vnd.application.etc'). Also cleans up some typings that were needed for older versions of TS.
> Fix dot diff

- nbdime/merging/strategies.py
- nbdime/tests/test_merge_notebooks_inline.py
Certain edge cases were incorrectly double identified as different types of conflicts. This ensures that the `inline-cell` strategy is now only used for conflicts on `cells`.
Fixes #379.
> Fixes for inline source merge strategy

- docs/source/changelog.md
- docs/source/config.rst
- nbdime/__main__.py
- nbdime/args.py
- nbdime/config.py
- nbdime/diffing/notebooks.py
- nbdime/nbdiffapp.py
- nbdime/tests/test_args.py
- nbdime/tests/test_cli_apps.py
Fix several issues with the config system / documentation:
- Fix an issue of configuration inheritance from sections.
- Improve config docs.
- Make `<command> --config` output include all available options, even unconfigured ones (but mark those as unconfigured).
- Fix a mistake in applying the `--details` ignore option.
> Config cleanup

- .travis.yml
- appveyor.yml
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/nodevenv.rst
It was not clear that this was one of many ways to install node, and therefore optional / opinionated. This should hopefully make it more apparent.
> Extract nodeenv install instructions

- nbdime/diffing/generic.py
- nbdime/diffing/notebooks.py
- nbdime/profiling.py
- nbdime/tests/test_diff_performance.py
Supersedes #237.
Difflib's ratio() method blows up for very large contents. This PR limits this problem for output comparison by giving a maximum length for text data when doing mimedata comparison. If both sides of the comparison are larger than this length, it will revert to strict equality instead of the slow `ratio()` method.
> Optimize text comparison for text MIME data

- docs/source/config.rst
- nbdime/args.py
- nbdime/config.py
Previously the config system didn't work fully for subcommands (e.g. `git-nbdiffdriver diff`).
Also renames the config option `source` to `sources` to be in line with the CLI argument.
> Fix config parsing for subcommands

- nbdime/tests/test_web.py
- nbdime/webapp/nbdimeserver.py
Ensure we can pass `localhost` as the IP to web entrypoints.
Related to #408.
> Ensure localhost is recognized as loopback

- nbdime/vcs/git/filter_integration.py
- nbdime/webapp/nb_server_extension.py
Always use shell=True for git filter call. This is what it seems that git does, so we should be ok. Also, the value comes from git config, which should require write access to modify.
Fixes #415.
> Fix filter integration, always use shell=True

- nbdime/args.py
- nbdime/tests/test_server_extension.py
- nbdime/webapp/nbdimeserver.py
- packages/labextension/package.json
- packages/labextension/schema/plugin.json
- packages/labextension/src/actions.ts
- packages/labextension/src/plugin.ts
- packages/labextension/src/widget.ts
- packages/labextension/style/index.css
- packages/nbdime/src/request/index.ts
- packages/webapp/src/app/common.ts
- packages/webapp/src/app/compare.ts
- packages/webapp/src/app/diff.css
- packages/webapp/src/app/diff.ts
- packages/webapp/src/app/merge.css
- packages/webapp/src/app/merge.ts
- Adds settings for lab extension. So far only one setting: `hideUnchanged` that is true by default.
- Changes default for web views to hide unchanged cells by default (but checkbox is still there).
- Adds a CLI option for web diff/merge entry points `--show-unchanged` to allow old behavior.
- Fixes a problem with base urls for some requests.
- Now shows a notice if all cells are unchanged and hidden ("No changes, [N] unchanged cell(s) hidden").
Resolves #401.
> Add CLI/lab option for hide unchanged cells. On by default.

- nbdime/args.py
- nbdime/ignorables.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/prettyprint.py
- nbdime/tests/conftest.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_hg_differ.py
- nbdime/tests/test_prettyprint.py
- nbdime/vcs/git/diffdriver.py
- nbdime/vcs/hg/diff.py
- nbdime/webapp/nb_server_extension.py
Expose the following options for configuring the prettyprint module:
- `--no-color`: Do not use ANSI color codes in the output.
- `--no-git`: Do not call out to `git` to format text diffs/conflicts.
- `--no-use-diff`: Do not call out to `diff`/`diff3` to format text diffs/conflicts.
Fixes #426.
> Expose config for pretty print

- nbdime/tests/test_server_extension.py
- nbdime/webapp/nb_server_extension.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/templates/nbdimepage.html
- packages/webapp/package.json
- packages/webapp/src/app/diff.ts
Behavior in jupyterlab rendermime changed previously. This uses the most recent way of specifying the latex typesetter. No change needed for the lab extension, as that should be configured from the application level.
Awaiting resolution of https://github.com/jupyterlab/jupyterlab/issues/5257 before merging to possibly clean up dependencies.
> Fix mathjax use in webapp

- nbdime/args.py
- nbdime/nbmergeapp.py
Now, if the 'base' argument is not supplied, it uses the null file as the default. This translates to an empty, minimal notebook  (`read_notebook(bfn, on_null='minimal')`).
Partially resolves #436.
>  Make nbmerge base argument optional

- nbdime/vcs/git/filter_integration.py
When using an older git version, we cannot support git-filter integration (unless someone else wants to contribute code to reliably parse previous output). With this change, we prevent nbdime from falling over completely when it encounters a version of git without support for the `-z` flag to `git check-attr`.
Fixes #440.
Fixes #417.
> Old git = no git-filter support

- nbdime/args.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/vcs/git/difftool.py
- nbdime/webapp/nbmergeweb.py
no-op on Python 3, casts bytes to text with sys.getfilesystemencoding on Python 2
ascii encoding is not respected, instead assuming the much more likely utf8 encoding if ascii is returned. If ascii is indeed correct, the behavior is the same anyway.
closes #452
> add Path type for path arguments

- packages/webapp/src/app/common.ts
- packages/webapp/src/app/diff.ts
- packages/webapp/src/app/merge.ts
Fixes an issue where initially hidden cells (unchanged) had a completely collapsed codemirror editor on unhide. The CM editor fails its initial size calculations if the cell is hidden, so it needs to be given the chance when it becomes visible. Most likely, it would be sufficient to call this on the first show, but for now we update on all shows.
> Ensure app widget is updated on cell unhide

- nbdime/webapp/nbdimeserver.py
otherwise the notebook handlers block access as a CORS / DNS-rebinding protection
closes #455
> set allow_remote_access when listening on non-localhost ip

- nbdime/webapp/nbdimeserver.py
Found running this in a container in linux, if `/dev/null` exists on the os then it will try to read from it and tip over.
> change the order of if statements so that missing is checked first

- packages/nbdime/src/styles/common.css
- packages/webapp/src/app/common.css
Prevent styling from bleeding into other environments, e.g. in the lab extension.
Fixes #445.
> Scope CSS for nbdime JS library

- nbdime/webapp/nbdimeserver.py
This avoids the application relabelling potential HTTP errors as 422 unprocessable entity.
It does however mean any exceptions other than ValueError and NotJSONError cause crashes which might not be desirable (though I couldn't see any other types of exception would likely come up?)
> provide user with detail from failed http requests

- nbdime/prettyprint.py
- setup.py
Implements feature requested in https://github.com/jupyter/nbdime/issues/456. Currently hard coded to colorize source as Python; needs to be parameterized to pass language to `find_lexer_class_by_name()` so as to select the appropriate lexer.
> Colorize source with pygments before displaying.

- nbdime/gitfiles.py
- nbdime/tests/test_server_extension.py
- nbdime/webapp/nb_server_extension.py
- nbdime/webapp/nbdimeserver.py
This change adds a server endpoint to diff two git refs for a single file. This is flexible to perform diffs across various points in the Git lifecycle such as diff'ing changes in the Working Tree, Index, or two arbitrary commits. There are two reserved refs WORKING and INDEX to designate the Working Tree and the git Index
A separate API was added to avoid using the "git:" prefix to designate git diffs and add many optional parameters in the existing `/api/diff`. This is backwards compatible, the existing `/api/diff` will work as expected.
Addresses #480 
```
curl -X POST \
http://localhost:8888/nbdime/api/diff \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d '{
"base": "git:Untitled1.ipynb"
}'
```
* Submitting early to get feedback. I'll add tests if the overall …
> Add a `/gitdiff` API 

- packages/nbdime/src/merge/model/notebook.ts
- packages/nbdime/test/src/merge/model.spec.ts
Fixes #488.
Existing code assumes MergeDecision with removerange is only ever paired with patch, so this prevents blowups.
This is based on initial patch from @vidartf.
> Handle addrange/removerange conflicts by splitting.

- nbdime/args.py
When git detects that it diffs renamed files, it passes two extra
undocumented parameters to the external diff program. One of the
parameters, rename_to, has been supported since 59aef29 (2016-05-03),
but the other has been omitted. This caused (a part of) #497.
This change adds support for the missing CLI parameter.
> Parse rename metadata CLI parameter

- setup.py
Also change image URLs to point to GitHub so they work on PyPI.
> Show README content as package description on PyPI

- .travis.yml
- nbdime/webapp/templates/nbdimepage.html
- packages/webapp/package.json
- packages/webapp/src/index.ts
No external requests for the webapps when running.
- Assume browsers support promises
- Remove require (nothng should use it?)
- Include font-awesome as part of the bundle (~80 kB).
Fixes #501.
> Remove run-time deps from webapps

- setup.py
Now that pytest-tornado has minimal maintenance again, we can switch back.
> fix test dependency

- nbdime/args.py
- nbdime/nbdiffapp.py
- nbdime/tests/conftest.py
- nbdime/tests/test_args.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_hg_differ.py
- nbdime/tests/test_merge_notebooks.py
Stop-gap fix for #529.
Does not implement the full "ideal" logic, but prevents "Ignore" config from always being overridden. With this change:
- If no flags are specified it will use the config values. If also no config is specified, it will behave as it currently does.
- If any flag is specified, it will override all config values that is affected by a flag, as it currently does.
> Stop gap measure to avoid always ignoring ignore config

- nbdime/nbmergeapp.py
- nbdime/utils.py
- nbdime/webapp/nbdimeserver.py
Git seems to prefer to give a zero-length base file if we have conclicting creation of the same file in two branches, instead of using the explicit missing file (/dev/null or NUL). This PR adds code to handle this behavior.
We still let nbdime fall over in most other cases where the file is "real", as empty .ipynb files are invalid JSON.
Fixes #536.
> Fix error with empty base in merge

- nbdime/diffing/notebooks.py
This prevents large text outputs from taking up a lot of time in comparison. As the value of very large outputs is low, the impact on performance should be worth the improved performance.
> Limit the size of stream outputs to diff

- .travis.yml
- appveyor.yml
- nbdime/tests/test_cli_apps.py
- nbdime/webapp/nbdimeserver.py
- packages/webapp/src/app/common.ts
- setup.py
`sendBeacon` allows us to send the request while not using syncchorous requests to block the closing of the browser tab.
> Use sendBeacon to send close requests

- docs/source/cli.rst
CLI flag for details was not included in docs, xref #556.
> add 'details' flag to CLI docs

- nbdime/tests/test_web.py
- nbdime/webapp/nbdimeserver.py
- setup.py
Relies on https://github.com/jupyter-server/jupyter_server_mathjax for mathjax static assets.
Fixes #573.
> Rely on jupyter-server-mathjax

- .github/workflows/tests.yml
- package.json
- packages/nbdime/jest.config.js
- packages/webapp/package.json
- packages/webapp/src/index.ts
Latest releases of some packages has broken the dev install build. This PR resolves those issues.
> Fix the dev build

- docs/source/installing.rst
This section currently looks a bit odd on the installation page, so I suggest moving the note on top and format it as an admonition.
Current appearance:
> Format note and code correctly on installation page

- nbdime/prettyprint.py
As addressed in https://github.com/jupyter/nbdime/issues/240 the
headers are printed in BLUE, which is hard to read when using git
integration in a dark terminal.
This allows for the color to remain the same, but just to brighten it up
such that is more readable.
Refs:
- https://github.com/tartley/colorama/blob/34703ece90fc4996727adff31502bad8a8e88066/demos/demo03.py#L15
modified:   prettyprint.py
> Make INFO text more readable in black terminal

- nbdime/webapp/nb_server_extension.py
> Compatible with asynchronous contentsmanager

- .github/workflows/tests.yml
- setup.py
After this merges, it would be great if a maintainer could create a new release, to formalize support for Python 3.11.
> support Python 3.11

- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_server_extension.py
- nbdime/webapp/nbdimeserver.py
- packages/webapp/src/app/common.ts
Fixes issues related to missing xsrf values due to our use of `navigator.sendBeacon` for closing the web tools. Also fixes a deprecation warning for missing `identity_provider`.
> Jupyter server 2.0 compatability fixes

- .github/workflows/tests.yml
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_hg_differ.py
- setup.py
The latter is available with Python 3.3 [1], and nbdime requires Python 3.6+ as per setup.py.
This change removes the need of an external library.
[1] https://docs.python.org/3/library/unittest.mock.html
> Replace mock with unittest.mock

- packages/nbdime/src/styles/merge.css
Fixes mixed approach observed in issue #678, where both syntax highlighting and diff chunk text coloring was observed in the central editor of the mergeview.
> Fix syntax highlighting issue in diffchunks.

- packages/nbdime/src/common/mergeview.ts
This is a follow-up to #673, something I noticed when looking into https://github.com/jupyter/nbdime/issues/676
For reference, this is the corresponding code on 3.2 branch:
https://github.com/jupyter/nbdime/blob/1b368a884405914e9b1861a445c20927f7c88a5b/packages/nbdime/src/common/mergeview.ts#L555-L572
it was also using `conflict` so I assume `picker` here on the master branch is a typo.
> Fix wrong picker marker (a typo during lab 4.0 migration)

- packages/labextension/package.json
- packages/nbdime/package.json
Similar to https://github.com/jupyterlab/jupyterlab/pull/14028
It follows error messages seen in @jupyterlab/git similar to that one:
```
WARNING in ./node_modules/nbdime/lib/upstreaming/flexpanel.js
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
Invalid dependencies may lead to broken watching and caching.
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not …
```
> Add src for sourcemap

- .readthedocs.yaml
and build with Python 3.11
builds are [failing](https://readthedocs.org/projects/nbdime/builds/22047074/) with missing `npm`.
> RTD: make sure nodes is present

- nbdime/args.py
- nbdime/tests/test_server_extension.py
- nbdime/webapp/nbdimeserver.py
- package.json
- packages/nbdime/src/common/basepanel.ts
- packages/nbdime/src/common/interfaces.ts
- packages/nbdime/src/common/mergeview.ts
- packages/nbdime/src/diff/widget/cell.ts
- packages/nbdime/src/diff/widget/metadata.ts
- packages/nbdime/src/diff/widget/notebook.ts
- packages/nbdime/src/diff/widget/output.ts
- packages/nbdime/src/merge/widget/cell.ts
- packages/nbdime/src/merge/widget/metadata.ts
- packages/nbdime/src/merge/widget/notebook.ts
- packages/webapp/src/app/diff.ts
- packages/webapp/src/app/merge.ts
Make collapseIdentical margin configurable
Improve base interfaces
This is extracted from #694 that is stuck on windows case.
> Make collapseIdentical margin configurable

- .github/workflows/tests.yml
- nbdime/args.py
- nbdime/config.py
- nbdime/webapp/nbmergeweb.py
- package-lock.json
- package.json
- packages/nbdime/src/common/mergeview.ts
- ui-tests/tests/nbdime-merge-test1.spec.ts
- Remove debug console.log
- Restore dep for update-dependency helper
- Set the CLI arg for showBase only for the nbmerge web
- Test the label change for showBase option
> Apply post-mortem review comments

- packages/nbdime/package.json
CSS were not listed in files to be included in the nbdime NPM package
> Add CSS files in nbdime package

- nbdime/_version.py
Follow-up of 4.0.0 release
Xref https://github.com/jupyter/nbdime/issues/659#issuecomment-1819387273
> Fix version parsing

- docs/source/cli.rst
- nbdime/webapp/nbdimeserver.py
- Fixes https://github.com/jupyter/nbdime/issues/749
- Reopens https://github.com/jupyter/nbdime/pull/756
While ideally we would rewrite nbdime to use a secure solution server it does not seem likely to happen any time soon. In the meantime we need to fix this even to allow the CI to pass and to let users to run `nbdime` server locally.
> Allow unauthenticated access to jupyter server
