- nbdime/diffing/generic.py
- nbdime/diffing/notebooks.py
- nbdime/diffing/snakes.py
Work on streamlining the highlevel diff algorithms.
> Refactor diff algorithms

- nbdime/diff_format.py
- nbdime/merging/generic.py
- nbdime/merging/notebooks.py
- nbdime/nbmergeapp.py
- nbdime/tests/test_merge_notebooks.py
This is just a few steps and half finished ideas, nothing much to see here yet. Just wanted to merge.
> Add merge strategies sketch

- nbdime/gitdifftool.py
- scripts/git-nbdifftool
- setup.py
Register with:
git nbdifftool config --enable [--global]
Use with:
git difftool [<commit> [<commit>]]
> Add git difftool prototype

- docs/source/api.md
- docs/source/cli.rst
- docs/source/conf.py
- docs/source/diffing.rst
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/merging.rst
- docs/source/overview.rst
- docs/source/plans.rst
Hello @martinal :sunny: 
I work with @minrk on Jupyter. I had a bit of free time this afternoon and did some formatting and editing on the draft docs for nbdime. Please let me know what you would like me to change/add/delete. Here's a rendered version of the proposed docs: http://carol-nbdime.readthedocs.org/en/doc-update/
> Edit and format the draft documentation

- nbdime/nbpatchapp.py
Simple mistype nbpatch vs nbdiff.
> Corrected nbpatch description

- .gitignore
Ignore Spyder IDE project files
> .gitignore: Ignore Spyder IDE project files

- nbdime/webapp/src/diffmodel.ts
guess Python, which is most likely for old notebooks, which is when this is likely to come up.
closes #53
> handle missing language

- nbdime/gitdiffdriver.py
- nbdime/nbdiffapp.py
- nbdime/prettyprint.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_prettyprint.py
- setup.py
> color terminal diffs with colorama

- README.md
- nbdime/diffing/notebooks.py
- nbdime/prettyprint.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/static/cm-merge.css
- nbdime/webapp/static/diff.css
- nbdime/webapp/webpack.config.js
- setup.py
includes javascript sources in install and README instructions for building.
Adds nbdiff-web for manual invocation, not just difftool.
> install the difftool

- nbdime/merging/chunks.py
- nbdime/nbdiffapp.py
Useful in other code to align several diffs simultaneously, typically local, remote and final merged.
> Refactor merge chunking to take N diffs

- nbdime/merge_format.schema.json
See #74 for discussion about the format.
In addition to describing the format, it should be useful for unit testing.
> Add a JSON schema describing merge decision format

- .travis.yml
- README.md
- nbdime/diffing/generic.py
- nbdime/gitmergedriver.py
- nbdime/merging/autoresolve.py
- nbdime/merging/decisions.py
- nbdime/merging/generic.py
- nbdime/tests/test_decision_tools.py
Bugfixes and minor changes to server side code.
> Server-side fixes

- .travis.yml
- README.md
- nbdime/diffing/generic.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/merging/autoresolve.py
- nbdime/merging/decisions.py
- nbdime/merging/generic.py
- nbdime/tests/test_decision_tools.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- setup.py
Adds CLI for launching merge webtool (loading the page will still fail), and adds CLI for git integration of mergetools.
Includes #78 .
> Mergetool server and mergetool git integration

- docs/source/cli.rst
- docs/source/diffing.rst
- docs/source/glossary.rst
- docs/source/installing.rst
- docs/source/merging.rst
- docs/source/testing.rst
- docs/source/usecases.rst
- nbdime/args.py
- nbdime/diff_format.schema.json
- nbdime/gitdiffdriver.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/merge_format.schema.json
- nbdime/merging/notebooks.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/tests/test_diff_format.py
- nbdime/tests/test_merge_format.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- requirements.txt
- setup.py
Several areas were cleaned up: 
- Refactors CLI arguments specification, cleaning up several issues related to them in the process.
- Fixes merge format JSON schema + adds JSON schema for diff format.
- Ensures setup.py runs correct npm commands after previous refactorization.
- Updates dependencies (setup.py, requirements.txt, docs).
- Add / improve docs.
> Cleanup: CLI, setup and docs

- docs/source/index.rst
- docs/source/vcs.rst
Initial suggestion for documentation of git integration.
> Add docs for version control (git) integration

- README.md
Make it explicit that npm needs to be installed to install this from source.
> Update README.md with npm requirement

- nbdime-web/src/merge/model.ts
- nbdime/merging/generic.py
- nbdime/webapp/package.json
- nbdime/webapp/testnotebooks/cellchange.ipynb
- nbdime/webapp/testnotebooks/local.ipynb
- nbdime/webapp/testnotebooks/remote.ipynb
- nbdime/webapp/testnotebooks/scrollA.ipynb
Just some minor cleanup/tuning.
> Minor fixes

- nbdime-web/src/diff/model.ts
- nbdime-web/src/merge/model.ts
- nbdime-web/src/merge/widget.ts
- nbdime/merging/notebooks.py
- nbdime/webapp/package.json
- nbdime/webapp/templates/merge.html
- setup.py
Various minor fixes, most important fix in merge cell deletion and metadata patch on other side.
Partially fixes
https://github.com/jupyter/nbdime/issues/64
but the execution_count handling issue is still left.
> Fix merge cell delete and patch

- .gitignore
- nbdime/tests/test_utils.py
- nbdime/utils.py
- nbdime/webapp/nbdimeserver.py
- setup.py
Should fix #51 together with the previous changes in 956f0e8f5149afc71d55c94fcca36a23e9905fa5, 0bca365fb482a6820d66d2ffb994fd5f252f99b6 and 2777cc91752fdd2ef2a42f3d1e0d4fffd33b3ae7 (already in master).
> Fix setup for distribution

- nbdime/merging/generic.py
- nbdime/prettyprint.py
- nbdime/tests/conftest.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_prettyprint.py
Adjust pretty-print use of `unified_diff` to have the output be more similar to that of git diff.
> Adjust pretty-print

- nbdime-web/src/common/mergeview.ts
- nbdime-web/src/merge/model/cell.ts
- nbdime-web/src/merge/widget.ts
Several minor fixes, enhancements and cleanups to various bits of the webapp code, see commit messages for details.
> Several fixes to the webapp code

- nbdime-web/src/request/index.ts
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/src/index.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
- Refactors close/save buttons. Fixes #111.
- Fixes issues with escaping/unescaping JSON args.
> Fix close button

- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/merge.html
- setup.py
Adds ability for diff and merge web interfaces to load notebooks from URLs.
Also includes some other minor fixes and improvements.
> Allow nbdime web interfaces to load URLs

- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/src/app/compare.ts
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/src/index.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
Implement index page, which will either perform a diff or a merge depending on how many filenames has been entered into the form.
Also fixes state management for back/forward navigation.
> Add smart index page

- nbdime-web/src/chunking/index.ts
- nbdime-web/src/common/mergeview.ts
- nbdime-web/src/diff/model/string.ts
- nbdime-web/src/diff/util.ts
- nbdime-web/src/merge/decisions.ts
- nbdime-web/typings/codemirror.d.ts
Fixed various issues, and introduces some new utility functions shared between different WIP branches. See commit log for details
> Various fixes and utilities

- nbdime/__main__.py
- nbdime/args.py
- nbdime/gitdiffdriver.py
- nbdime/gitdifftool.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/log.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
Ensures all entry points initializes a root logger, and ensures web servers use logging instead of printing. Also adds a corresponding CLI arg to set the log level, which defaults to `"INFO"`.
> Logging fixes and enhancements

- nbdime-web/src/diff/widget/cell.ts
- nbdime-web/src/diff/widget/output.ts
- nbdime-web/src/styles/common.css
- nbdime-web/src/styles/diff.css
- nbdime-web/src/styles/merge.css
- nbdime-web/src/styles/variables.css
- nbdime/webapp/src/app/common.css
- nbdime/webapp/src/app/common.ts
- nbdime/webapp/src/app/diff.css
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.css
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/src/index.ts
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/mergetool.html
Adjusts/fixes the styles applied on outputs of one-sided diffs.
Fixes #129 .
> Adjust output diff view

- nbdime-web/src/styles/diff.css
Fixes small errors after #130.
> Adjust output styles of diffs

- .gitignore
- MANIFEST.in
- nbdime/webapp/src/tsconfig.json
- setup.py
This should adjust file inclusions for sdist/bdist with regards to web code.
> Adjust which files get included in sdist/bdist

- setup.py
Usage:
pip install . --install-option="--skip-npm"
Addresses https://github.com/jupyter/nbdime/issues/113
Maybe there's a more standard way of doing this but this works.
Also nice while working only on python parts as the npm install is really slow.
> Add setup.py option --skip-npm

- nbdime/__main__.py
- nbdime/args.py
- nbdime/diff_format.py
- nbdime/merging/autoresolve.py
- nbdime/merging/decisions.py
- nbdime/merging/notebooks.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/nbshowapp.py
- nbdime/prettyprint.py
- nbdime/tests/conftest.py
- nbdime/tests/files/inline-conflict--1.ipynb
- nbdime/tests/files/inline-conflict--2.ipynb
- nbdime/tests/files/inline-conflict--3.ipynb
- nbdime/tests/test_autoresolve.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_prettyprint.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- setup.py
Fixes in inline-source formatting: newline bug and using ||| and === like diff3 does.
NB! This branch sits on top of the prettyprint branch, I could rebase this but expect that one to be merged soon anyway?
> Fix inline merge conflict

- docs/source/vcs.rst
- nbdime/__main__.py
- nbdime/args.py
- nbdime/gitdiffdriver.py
- nbdime/gitdifftool.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/log.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/nbshowapp.py
- nbdime/prettyprint.py
- nbdime/tests/test_cli_apps.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- scripts/git-nbdifftool
- scripts/nbdiff
- scripts/nbmerge
- scripts/nbpatch
- setup.py
- remove non-web git diff/merge tools (and remove web from names of remaining diff/merge tools)
- consolidate init_logging calls
- trigger set_nbdime_log_level automatically with argparse Action
- expose `nbdime.log.info,error,etc.` log functions
- remove nbpatch entrypoint (leave code alone)
> Update logging and entrypoints

- README.md
- docs/source/cli.rst
- docs/source/diffing.rst
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/merging.rst
- docs/source/restapi.md
- docs/source/testing.rst
This is a first pass at updating the docs for release. Several areas are still in progress.
The gist:
- add Quickstart, summary to index
- high-level "how do I use it" for each entrypoint added to cli.rst
- lots of places for screenshots / illustrations (still to be created)
cc @willingc for doc review
> [WIP] update docs for release

- nbdime/__main__.py
- setup.py
- Adds `nbdime` as console entry point to main dispatch.
- Renames main dispatch sub-commands (removes `nb` prefix).
- Adds main dispatch sub-command (`mergetool`)
Fixes #88.
> Mergetool command

- docs/source/conf.py
Changing back to version Sphinx 1.3 minimum version so RTD will build.
> Update the sphinx version for RTD

- docs/doc-requirements.txt
- docs/source/cli.rst
- docs/source/diffing.rst
- docs/source/merging.rst
- docs/source/testing.rst
- docs/source/vcs.rst
- Add doc-requirements.txt for local builds
- Edit all installation and usage docs
- Correct TODO directives to suppress the notes from displaying on RTD
> Edit docs 

- nbdime/args.py
- nbdime/diffing/notebooks.py
- nbdime/merging/autoresolve.py
- nbdime/merging/decisions.py
- nbdime/merging/notebooks.py
- nbdime/nbmergeapp.py
- nbdime/patching.py
- nbdime/prettyprint.py
- nbdime/tests/conftest.py
- nbdime/tests/test_autoresolve.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/utils.py
Introduces support for git merge-file and diff3 for rendering inline source conflicts.
Also contains a few smaller fixes and edits I've done while looking around the code.
Includes the log fix from @minrk.
Inlining of source and output conflicts do _not_ work as expected yet.
I'd like to have this branch merged now because it contains various useful small fixes, and will create a new PR for conflict inlining later.
> Various fixes

- nbdime/log.py
- nbdime/webapp/nbdimeserver.py
attach things to app.settings
rather than module-global
> remove some global nbdimeserver state

- docs/source/diffing.rst
- docs/source/glossary.rst
- docs/source/merging.rst
- docs/source/restapi.md
- docs/source/usecases.rst
This PR updates the formatting in grammar of the second half of the documentation.
> Edit formatting and grammar in docs

- docs/source/index.rst
I love the new screenshots :smile:
I've added accessibility alt-txt and captions to the images on the index page to provide the reader more context when first reading the doc.
> Add captions and alt text to images in index doc

- .travis.yml
- README.md
- nbdime/gitdiffdriver.py
- nbdime/gitdifftool.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/tests/conftest.py
- nbdime/tests/fixtures.py
- nbdime/tests/test_cli_apps.py
- nbdime/utils.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- requirements.txt
- setup.py
> improve CLI coverage

- .travis.yml
> Use node 6 for travis

- docs/source/cli.rst
- docs/source/diffing.rst
- docs/source/index.rst
update merge decisions and place nbdiff-web screenshot in a couple more places.
> finish todo items in docs

- nbdime-web/src/common/mergeview.ts
- nbdime-web/src/merge/widget/cell.ts
- nbdime-web/src/styles/merge.css
Various fixes
- Highlighting for conflicts now disappears when conflict is unmarked
- The outputs that are picked now also get saved!
- Styling issue in mergeview
> Quickfixes to prerelease

- nbdime/__main__.py
Defaults to *.ipynb and filters out non-ipynb files with a warning.
> Let nbdime mergetool take filename arguments.

- nbdime/diff_format.py
- nbdime/diffing/generic.py
- nbdime/diffing/notebooks.py
- nbdime/merging/autoresolve.py
- nbdime/merging/chunks.py
- nbdime/merging/decisions.py
- nbdime/merging/notebooks.py
- nbdime/tests/files/attachment--empty_attachments_list.ipynb
Tries to mark outputs better based on diffs instead of throwing all outputs between markers with output-strategy inline.
Also please review the changes in diff for attachments, these are untested.
> Output merge improvements

- docs/source/vcs.rst
probably cut-n-paste oversights.
> diff and merge confusion

- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
diff/merge web/tool entry points now log their url for easy copy-paste. Params information is relegated to debug level.
Fixes #208.
> Adjust logging when starting server

- README.md
- docs/source/testing.rst
follow-up from #206
also fix a few links in the README.
> remove redundant 'in the nbdime-web folder'

- .gitignore
- nbdime-web/src/common/mergeview.ts
- nbdime-web/src/diff/model/index.ts
- nbdime-web/src/diff/model/output.ts
- nbdime-web/src/diff/model/renderable.ts
- nbdime-web/src/diff/widget/notebook.ts
- nbdime-web/src/diff/widget/output.ts
- nbdime-web/src/diff/widget/renderable.ts
- nbdime-web/src/merge/widget/notebook.ts
- nbdime-web/src/styles/diff.css
- nbdime-web/src/styles/merge.css
- nbdime-web/src/styles/variables.css
- nbdime-web/typings/codemirror.d.ts
- nbdime/webapp/package.json
- nbdime/webapp/src/app/common.css
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
- nbdime/webapp/webpack.config.js
- Clean up paths for static resources.
- Have diff and merge view start rendering cell widgets as they become ready. Previously, the rendering could be severely delayed from laying out the CodeMirror editors for large notebooks. Some other optimizations were also applied.
- Improve stylings, particularly of outputs in diff.
- Refactors renderable models / widgets in preparation for #99.
> Various web improvements

- nbdime/gitdiffdriver.py
- nbdime/gitmergedriver.py
- nbdime/utils.py
> ensure gitattributes dir exists before writing a file in it

- nbdime/prettyprint.py
> Bugfix: Add indexing bounds check in prettyprint

- docs/source/vcs.rst
- nbdime/gitdiffdriver.py
- nbdime/gitdifftool.py
- nbdime/gitmergedriver.py
- nbdime/gitmergetool.py
- nbdime/tests/test_decision_tools.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbmergetool.py
> Document `--system` flag

- docs/source/cli.rst
- docs/source/index.rst
- docs/source/vcs.rst
- nbdime/__main__.py
- nbdime/tests/test_cli_apps.py
Simply calls all four git-nb* commands with the supplied arguments.
Resolves #241.
> Add `nbdime config-git` command

- nbdime-web/src/common/dragpanel.ts
Fix like in jupyterlab/jupyterlab#1650.
> Web: Prevent selecting when dragging cell/output

- nbdime-web/src/request/index.ts
- nbdime/__main__.py
- nbdime/args.py
- nbdime/tests/conftest.py
- nbdime/tests/fixtures.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_diff_format.py
- nbdime/tests/test_merge_format.py
- nbdime/tests/test_web.py
- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
- nbdime/webapp/src/app/common.ts
- nbdime/webapp/src/app/compare.ts
- nbdime/webapp/src/app/diff.ts
- nbdime/webapp/src/app/merge.ts
- nbdime/webapp/webutil.py
- setup.py
> support base-url

- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
cdn.mathjax.org is [shutting down](https://www.mathjax.org/cdn-shutting-down/)
closes #278
> get mathjax from cdnjs

- setup.py
See https://groups.google.com/forum/#!msg/jupyter/T2Y-kw5eRnQ/QAJ0M0IRBgAJ.
> Add 'Framework :: Jupyter' to setup classifiers

- .travis.yml
- appveyor.yml
- nbdime/tests/test_js_artifacts_installed.py
- setup.py
- setupbase.py
Develop install can hide issues with setup scripts, as seen in #283.
> Do not use develop install on CI

- docs/source/changelog.md
- docs/source/index.rst
- docs/source/vcs.rst
- nbdime/webapp/templates/diff.html
- nbdime/webapp/templates/difftool.html
- nbdime/webapp/templates/index.html
- nbdime/webapp/templates/merge.html
- nbdime/webapp/templates/mergetool.html
and bump mathjax to latest and tweak a few small things in the docs that I noticed.
cc @vidartf @JamiesHQ
> Changelog for 0.3

- docs/source/cli.rst
Adds documentation for the diff options for which parts to process.
Resolves #291.
> Document ignorable flags

- docs/source/vcs.rst
- nbdime/args.py
- nbdime/gitdiffdriver.py
- nbdime/nbdiffapp.py
- nbdime/tests/conftest.py
- nbdime/tests/test_args.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_web.py
- nbdime/tests/utils.py
- nbdime/webapp/nbdiffweb.py
- setup.py
This is my first contribution to jupyter family.
I've added webdiff driver for git.
> ENH: webdiff git driver added

- appveyor.yml
- docs/source/vcs.rst
- nbdime/__main__.py
- nbdime/args.py
- nbdime/diffing/directorydiff.py
- nbdime/tests/conftest.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_directory_differ.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_hg_differ.py
- nbdime/tests/utils.py
- nbdime/vcs/__init__.py
- nbdime/vcs/git/__init__.py
- nbdime/vcs/git/diffdriver.py
- nbdime/vcs/git/difftool.py
- nbdime/vcs/git/mergedriver.py
- nbdime/vcs/git/mergetool.py
- nbdime/vcs/hg/__init__.py
- nbdime/vcs/hg/diff.py
- nbdime/vcs/hg/diffweb.py
- nbdime/vcs/hg/merge.py
- nbdime/vcs/hg/mergeweb.py
- nbdime/webapp/nbdimeserver.py
- setup.py
> Add mercurial entry points

- nbdime/diff_format.py
- nbdime/diff_utils.py
- nbdime/diffing/generic.py
- nbdime/diffing/notebooks.py
- nbdime/diffing/seq_difflib.py
- nbdime/diffing/sequences.py
- nbdime/diffing/snakes.py
- nbdime/merging/chunks.py
- nbdime/merging/decisions.py
- nbdime/merging/generic.py
- nbdime/merging/strategies.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/patching.py
- nbdime/prettyprint.py
- nbdime/utils.py
- nbdime/vcs/git/difftool.py
- Adds assert messages. Fixes #162.
- Adds comments and docstrings, does some linting.
- Moves some functions from merging/generic to a new file merging/strategies. The moved functions should all be related to resolution of merge conflicts given a specific strategy.
> Housekeeping

- nbdime/prettyprint.py
rather than the diff, status tuple
> return the correct string from diff_render_with_diff

- setupbase.py
ref: 12a7761d4a13d8446f1496126a810248a1441d21
> update vendored setupbase from jupyter-packaging

- .travis.yml
- nbdime/nbpatchapp.py
- nbdime/nbshowapp.py
- nbdime/tests/test_cli_apps.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_hg_differ.py
- nbdime/tests/test_merge_format.py
- nbdime/tests/test_merge_notebooks.py
- nbdime/tests/test_merge_notebooks_inline.py
- nbdime/tests/test_web.py
- setup.py
Drops support for Python 3.3. Also updates tests for using pytest 3.3.
> Drop Python 3.3

- nbdime/webapp/nbdimeserver.py
> Allow files for difftool to be read multiple times

- setup.py
> Put lower bound on jinja2 dependency

- packages/nbdime/src/common/dragpanel.ts
- packages/nbdime/src/common/exceptions.ts
- packages/nbdime/src/merge/model/notebook.ts
- packages/nbdime/src/merge/widget/dragdrop.ts
- packages/nbdime/src/merge/widget/notebook.ts
- packages/nbdime/src/merge/widget/output.ts
- packages/nbdime/src/request/index.ts
- packages/nbdime/src/styles/merge.css
This is a follow up to #347. Closes #345.
> Concurrent insert conflict resolution web

- docs/source/config.rst
- docs/source/index.rst
- nbdime/__main__.py
- nbdime/args.py
- nbdime/config.py
- nbdime/nbdiffapp.py
- nbdime/nbmergeapp.py
- nbdime/nbpatchapp.py
- nbdime/nbshowapp.py
- nbdime/tests/test_args.py
- nbdime/vcs/git/diffdriver.py
- nbdime/vcs/git/difftool.py
- nbdime/vcs/git/mergedriver.py
- nbdime/vcs/git/mergetool.py
- nbdime/vcs/hg/diff.py
- nbdime/vcs/hg/diffweb.py
- nbdime/vcs/hg/merge.py
- nbdime/vcs/hg/mergeweb.py
Add a config system. Currently it only adds the appropriate CLI arguments.
This differs from the config system used elsewhere in Jupyter by: Adding different configurable sections based on entry points, and entry point categories.
> Add config system

- packages/labextension/package.json
- packages/labextension/src/actions.ts
- packages/labextension/src/index.ts
- packages/labextension/src/plugin.ts
- packages/labextension/src/tsconfig.json
- packages/labextension/src/utils.ts
- packages/labextension/src/widget.ts
- packages/labextension/style/index.css
- packages/nbdime/src/styles/common.css
- packages/nbdime/src/styles/diff.css
- packages/nbdime/src/styles/merge.css
- packages/nbdime/src/styles/variables.css
- packages/webapp/src/app/diff.css
- setup.py
Builds on the server extension in #297, and adds a jupyter lab extension.
> Add jupyter lab extension

- docs/source/extensions.rst
- docs/source/installing.rst
- jupyter-config/jupyter_notebook_config.d/nbdime.json
- jupyter-config/nbconfig/notebook.d/nbdime.json
- nbdime/__main__.py
- packages/labextension/style/index.css
- setup.py
- Enable extensions on default.
- Add command for disabling extensions.
- Fix problem with header styling for labextension.
> Extensions cleanup

- packages/labextension/src/index.ts
- packages/labextension/src/plugin.ts
- packages/labextension/src/widget.ts
- packages/labextension/style/index.css
- packages/nbdime/package.json
- packages/nbdime/src/common/collapsible.css
- packages/nbdime/src/styles/common.css
- packages/nbdime/src/styles/variables.css
Handle focus better, and integrate stylings further with that of jupyterlab.
> Lab extension fixes

- setup.py
Ensure e.g. python 3.2 is invalidated.
> Fix python spec in setup.py

- packages/nbdime/src/styles/diff.css
Minor styling fix. Needed to ensure output hover menu always has room.
> Ensure rendered output minimum height

- docs/source/config.rst
- nbdime/config.py
- nbdime/webapp/nb_server_extension.py
- Fixes JSON format for config example.
- Adds config section for front end extensions so that custom ignore config gets picked up. Adds a documentation section outlining it.
Fixes #383.
> Add front end extension config section

- jupyter-config/nbconfig/notebook.d/nbdime.json
Fix reference to classic notebook extension location.
Fixes #387.
> Fix nbextension config data file

- nbdime/config.py
- nbdime/webapp/nb_server_extension.py
> Ensure server extension uses ignorable flags

- packages/nbdime/src/common/editor.ts
> Fix readonly focus + copying

- README.md
- docs/source/installing.rst
This adds instructions for how to perform a developer install for working on the jupyter extensions of the code (notebook and lab extensions).
> Document the develop install for Jupyter extensions

- nbdime/args.py
> Tweak printing of config

- packages/webapp/package.json
> Fix inter-package dependency

- packages/labextension/src/widget.ts
- packages/nbdime/src/request/index.ts
- packages/nbdime/src/styles/diff.css
- packages/nbdime/src/styles/merge.css
- packages/webapp/src/app/common.css
- packages/webapp/src/app/merge.ts
- Fixes broken request code when saving mergetool results (closes #404).
- Fixes styling for mimetype selection of outputs in unchanged cells.
- Fixes margin for unchanged cells in merge tool.
> Fix mergetool save ++

- docs/source/cli.rst
> Fix outdated nbmerge flags in docs

- nbdime/webapp/templates/nbdimepage.html
> Always use https for font-awesome

- nbdime/webapp/templates/nbdimepage.html
- package-lock.json
- package.json
> Fix styling issue

- nbdime/webapp/nbdifftool.py
- nbdime/webapp/nbdiffweb.py
- nbdime/webapp/nbdimeserver.py
- nbdime/webapp/nbmergetool.py
- nbdime/webapp/nbmergeweb.py
Fixes #476 .
Not obvious to me why these were not included in the first place. Did we forget about them, or did we leave them out for some reason? If so, we have not been consistent in excluding them.
@minrk Do you remember anything about this? I have an echo of a memory that we might have done this on purpose for some reason, but I cannot for the life of me remember what that reason could be, and I find no clues in code / git history either.
> Use config for webapps

- .travis.yml
- appveyor.yml
- nbdime/_version.py
- setup.py
Drops support for Python 2 (EOL next month) and Python 3.4 (EOL earlier this year)
> Require Python 3.5

- .travis.yml
- appveyor.yml
- docs/source/installing.rst
- nbdime/tests/conftest.py
- nbdime/tests/test_git_diffdriver.py
- nbdime/tests/test_git_filter_integration.py
- nbdime/tests/test_web.py
- nbdime/webapp/nbdimeserver.py
- packages/nbdime/src/common/collapsible.css
- packages/nbdime/src/common/collapsiblepanel.ts
- packages/nbdime/src/patch/common.ts
Fixes some issues:
- Minor typings and typos cleanup
- Ensure nbdime works on Windows with Python 3.8
- Fix some icon issues for Jupyterlab 2.0 (xref discussion in https://github.com/jupyter/nbdime/pull/512)
> Cleanup and lab 2.0 fixes

- nbdime/notebook_ext/index.js
- nbdime/notebook_ext/nbdime.yaml
> Add extensions configurator

- nbdime/notebook_ext/index.js
- nbdime/notebook_ext/nbdime.yaml
First attempt at nbdime extensions configurator.
> Addresses: https://github.com/jupyter/nbdime/issues/499

- packages/labextension/src/widget.ts
- setup.py
Due to an update in JupyterLab, dev build was failing. This single line change seems to have fixed it. It was caused by the Jupyterlab/services package that has updated it's API.
This is referred to in these issues – #531 and https://github.com/jupyterlab/jupyterlab/issues/8736
Please let me know if I should do anything else for the PR to be accepted.
> Fix bug caused by recent version Jupyter Lab

- nbdime/merging/strategies.py
- nbdime/tests/test_merge_notebooks_inline.py
- packages/nbdime/src/diff/diffentries.ts
- packages/nbdime/src/merge/decisions.ts
- packages/nbdime/test/src/merge/decisions.spec.ts
Fixes #496, and fixes another issue that those notebooks also exposed in the inline merge resolution.
> Merge fixes

- packages/nbdime/package.json
- packages/nbdime/test/src/common/mergeview.spec.ts
- packages/nbdime/test/src/merge/widget.spec.ts
This PR addresses the comments made in #576
> Follow-up of #576

- packages/nbdime/src/diff/model/renderable.ts
> Fix missed update from copy/paste

- docs/source/config.rst
Ref: https://github.com/jupyter/nbdime/issues/521#issuecomment-621261475
> Doc: precise configuration option

- nbdime/config.py
Avoids implicit dependency that is no longer required
> Remove usage of ipython_genutils

- docs/source/index.rst
I simply hyperlinked the grant numbers and added a missing space.
> Copyedits to docs/source/index.rst

- nbdime/merging/strategies.py
Fixes: https://github.com/jupyter/nbdime/issues/626
> Update cell marker format to use bold correctly

- packages/webapp/src/app/common.ts
> Correctly send exit code 0

- .readthedocs.yaml
> Add `.readthedocs.yml` config file

- .github/workflows/update-integration-tests.yml
Switch from hub CLI (remove from GH runners on October 2nd) to gh CLI.
> Switch from hub to gh CLI

- package-lock.json
- package.json
- packages/labextension/package.json
- packages/nbdime/package.json
- packages/webapp/package.json
Follow-up of https://github.com/jupyter/nbdime/issues/659#issuecomment-1794820102
> Bump JS packages to rc.0

- .github/workflows/update-integration-tests.yml
Update integration tests workflow from the most recent `extension-template` (https://github.com/jupyterlab/extension-template)
> Update integration tests workflow

- package-lock.json
fixes: https://github.com/jupyter/nbdime/issues/759
> Bump axios to version 1.7.4
